version: '3.8'
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Blog
    networks:
      - newtwork
  blog7-spi2:
    build: ./Blog7-SPI2 
    ports:
      - "80:5085"
      - "443:7086"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - newtwork

networks:
  newtwork:

